// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nessafesta.web.converter;

import net.nessafesta.web.converter.EventConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EventConverter_Roo_Configurable {
    
    declare @type: EventConverter: @Configurable;
    
}
