// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nessafesta.web.converter;

import net.nessafesta.web.converter.InviteesGroupConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InviteesGroupConverter_Roo_Configurable {
    
    declare @type: InviteesGroupConverter: @Configurable;
    
}
