// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nessafesta.web;

import net.nessafesta.web.AttendeesGroupBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AttendeesGroupBean_Roo_Configurable {
    
    declare @type: AttendeesGroupBean: @Configurable;
    
}
