// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nessafesta.web;

import java.io.Serializable;
import net.nessafesta.web.AttendeesGroupBean;

privileged aspect AttendeesGroupBean_Roo_Serializable {
    
    declare parents: AttendeesGroupBean implements Serializable;
    
    private static final long AttendeesGroupBean.serialVersionUID = 1L;
    
}
