// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nessafesta.web;

import java.io.Serializable;
import net.nessafesta.web.InviteesGroupBean;

privileged aspect InviteesGroupBean_Roo_Serializable {
    
    declare parents: InviteesGroupBean implements Serializable;
    
    private static final long InviteesGroupBean.serialVersionUID = 1L;
    
}
